# Generated by Django 2.2 on 2020-04-20 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20200420_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Deleted User'), to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
