# Generated by Django 2.2 on 2020-04-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ph_number',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
