# Generated by Django 2.2 on 2020-04-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_timestamp'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='Tag',
        ),
    ]
