# Generated by Django 2.2 on 2020-04-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200413_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='prodcuts',
            new_name='products',
        ),
    ]
